[[websites]]
url = "https://jm.dev"

[[websites]]
url = "https://0xadada.pub"

[[websites]]
url = "http://tenderlovemaking.com"

[[websites]]
url = "https://blogs.msdn.com/b/abhinaba"

[[websites]]
url = "http://masnun.com"

[[websites]]
url = "https://adambard.com/blog"

[[websites]]
url = "http://dtrace.org/blogs/ahl"

[[websites]]
url = "http://www.adamtuliper.com"

[[websites]]
url = "https://addyosmani.com/blog"

[[websites]]
url = "https://blog.acolyer.org"

[[websites]]
url = "http://alanstorm.com"

[[websites]]
url = "https://arogozhnikov.github.io"

[[websites]]
url = "https://infrequently.org"

[[websites]]
url = "http://akaptur.com"

[[websites]]
url = "https://www.amitmerchant.com"

[[websites]]
url = "http://aarvik.dk"

[[websites]]
url = "https://computer.forensikblog.de/en"

[[websites]]
url = "http://www.andrewcbancroft.com"

[[websites]]
url = "https://blog.bramp.net"

[[websites]]
url = "https://blog.andrewray.me"

[[websites]]
url = "http://aakinshin.net/blog"

[[websites]]
url = "http://antirez.com/latest/0"

[[websites]]
url = "https://ariejan.net"

[[websites]]
url = "https://ariya.io"

[[websites]]
url = "http://lucumr.pocoo.org"

[[websites]]
url = "http://www.2ality.com"

[[websites]]
url = "http://bad-concurrency.blogspot.com"

[[websites]]
url = "https://www.wefearchange.org"

[[websites]]
url = "http://www.bfilipek.com"

[[websites]]
url = "https://benmccormick.org"

[[websites]]
url = "http://www.billthelizard.com"

[[websites]]
url = "https://bjornjohansen.no"

[[websites]]
url = "https://blog.blakeerickson.com"

[[websites]]
url = "http://blog.blundellapps.co.uk"

[[websites]]
url = "https://bohops.com"

[[websites]]
url = "http://rhodesmill.org/brandon"

[[websites]]
url = "https://brendaneich.com"

[[websites]]
url = "http://www.brendangregg.com/blog"

[[websites]]
url = "https://medium.com/@elbrujohalcon"

[[websites]]
url = "http://dtrace.org/blogs/bmc"

[[websites]]
url = "https://carlosbecker.com"

[[websites]]
url = "https://www.chenhuijing.com/blog"

[[websites]]
url = "http://thelazylog.com"

[[websites]]
url = "https://www.metachris.com/blog"

[[websites]]
url = "http://nullprogram.com"

[[websites]]
url = "http://blog.claymcleod.io"

[[websites]]
url = "http://www.cimgf.com"

[[websites]]
url = "https://codewithstyle.info"

[[websites]]
url = "https://tympanus.net/codrops"

[[websites]]
url = "https://medium.com/dailyjs"

[[websites]]
url = "http://dailytechvideo.com"

[[websites]]
url = "https://danluu.com"

[[websites]]
url = "http://code.dblock.org"

[[websites]]
url = "https://medium.com/@dschmidt1992"

[[websites]]
url = "http://www.datchley.name"

[[websites]]
url = "http://www.dabeaz.com/blog.html"

[[websites]]
url = "https://dave.cheney.net"

[[websites]]
url = "https://davidwalsh.name"

[[websites]]
url = "http://deanhume.com"

[[websites]]
url = "http://deborah-digges.github.io"

[[websites]]
url = "https://hookrace.net"

[[websites]]
url = "https://yurichev.com/blog"

[[websites]]
url = "http://www.dereuromark.de"

[[websites]]
url = "https://www.discovermeteor.com/blog"

[[websites]]
url = "https://domenicoluciani.com"

[[websites]]
url = "https://dotdev.co"

[[websites]]
url = "http://dragan.rocks"

[[websites]]
url = "http://www.gajotres.net"

[[websites]]
url = "https://drewdevault.com"

[[websites]]
url = "http://blog.edankwan.com"

[[websites]]
url = "http://www.practicallyefficient.com"

[[websites]]
url = "https://hyegar.com"

[[websites]]
url = "https://eaf4.com"

[[websites]]
url = "http://elegantcode.com"

[[websites]]
url = "http://eli.thegreenplace.net"

[[websites]]
url = "https://medium.com/javascript-scene"

[[websites]]
url = "https://ericlippert.com"

[[websites]]
url = "https://erikrunyon.com"

[[websites]]
url = "http://evanhahn.com"

[[websites]]
url = "http://www.evanjones.ca/chronological.html"

[[websites]]
url = "http://www.evanmiller.org"

[[websites]]
url = "https://blog.evantahler.com"

[[websites]]
url = "http://fbrnc.net"

[[websites]]
url = "https://blog.fedecarg.com"

[[websites]]
url = "https://tomassetti.me"

[[websites]]
url = "https://blog.filippo.io"

[[websites]]
url = "https://murze.be"

[[websites]]
url = "https://glebbahmutov.com/blog"

[[websites]]
url = "http://glennengstrand.info"

[[websites]]
url = "https://www.darkcoding.net"

[[websites]]
url = "http://ggajos.com"

[[websites]]
url = "http://neopythonic.blogspot.com"

[[websites]]
url = "https://firstdoit.com"

[[websites]]
url = "https://haydenjames.io"

[[websites]]
url = "https://conductofcode.io"

[[websites]]
url = "https://henrikwarne.com"

[[websites]]
url = "http://highscalability.com"

[[websites]]
url = "http://huonw.github.io"

[[websites]]
url = "http://blog.hypriot.com"

[[websites]]
url = "https://themodernlife.github.io"

[[websites]]
url = "http://iansommerville.com/systems-software-and-technology"

[[websites]]
url = "https://idontgetoutmuch.wordpress.com"

[[websites]]
url = "http://stdout.in"

[[websites]]
url = "http://ieftimov.com"

[[websites]]
url = "https://www.igvita.com"

[[websites]]
url = "https://codewithoutrules.com"

[[websites]]
url = "https://ivanursul.com"

[[websites]]
url = "https://jack.ofspades.com"

[[websites]]
url = "https://jaketrent.com"

[[websites]]
url = "http://jakewharton.com/blog"

[[websites]]
url = "http://jakeyesbeck.com"

[[websites]]
url = "http://prog21.dadgum.com"

[[websites]]
url = "http://jlongster.com/archive"

[[websites]]
url = "http://weblog.jamisbuck.org"

[[websites]]
url = "https://idiosyncratic-ruby.com"

[[websites]]
url = "http://blog.jayfields.com"

[[websites]]
url = "https://blog.codinghorror.com"

[[websites]]
url = "http://preshing.com"

[[websites]]
url = "https://jeremykun.com"

[[websites]]
url = "https://jerrygamblin.com"

[[websites]]
url = "https://jes.al"

[[websites]]
url = "https://blog.jessfraz.com"

[[websites]]
url = "http://www.blackbytes.info"

[[websites]]
url = "https://joearms.github.io"

[[websites]]
url = "https://begriffs.com"

[[websites]]
url = "https://www.joelonsoftware.com"

[[websites]]
url = "http://johannesbrodwall.com"

[[websites]]
url = "https://johnresig.com/category/blog"

[[websites]]
url = "http://www.johnwittenauer.net"

[[websites]]
url = "http://www.jonkensy.com"

[[websites]]
url = "https://codeblog.jonskeet.uk"

[[websites]]
url = "https://blog.cugu.eu"

[[websites]]
url = "http://www.born2data.com"

[[websites]]
url = "https://snook.ca"

[[websites]]
url = "http://blog.reverberate.org"

[[websites]]
url = "https://joshtronic.com"

[[websites]]
url = "https://jtreminio.com"

[[websites]]
url = "https://jvns.ca"

[[websites]]
url = "https://blog.jgrossi.com"

[[websites]]
url = "https://www.justinweiss.com/articles/archives"

[[websites]]
url = "https://juristr.com/blog"

[[websites]]
url = "https://useyourloaf.com"

[[websites]]
url = "https://hendry.iki.fi"

[[websites]]
url = "https://kev.inburke.com"

[[websites]]
url = "https://medium.com/@kirill_shevch"

[[websites]]
url = "https://aphyr.com"

[[websites]]
url = "http://lambda-the-ultimate.org"

[[websites]]
url = "https://lg.io"

[[websites]]
url = "https://iridakos.com"

[[websites]]
url = "http://lea.verou.me"

[[websites]]
url = "http://blog.lerner.co.il"

[[websites]]
url = "http://lifepluslinux.blogspot.in"

[[websites]]
url = "https://liveoverflow.com/blog/index.html"

[[websites]]
url = "https://loige.co"

[[websites]]
url = "http://manu.sporny.org"

[[websites]]
url = "https://enoent.fr"

[[websites]]
url = "https://blog.rinesi.com"

[[websites]]
url = "http://ocramius.github.io"

[[websites]]
url = "https://idea.popcount.org"

[[websites]]
url = "http://lackingrhoticity.blogspot.de"

[[websites]]
url = "https://martinfowler.com"

[[websites]]
url = "https://maryrosecook.com/blog"

[[websites]]
url = "https://matt.aimonetti.net"

[[websites]]
url = "https://www.mattcutts.com/blog"

[[websites]]
url = "http://matt.might.net/articles"

[[websites]]
url = "http://mattwarren.org"

[[websites]]
url = "https://blog.cryptographyengineering.com"

[[websites]]
url = "https://michaelcrump.net"

[[websites]]
url = "http://www.michaelgallego.fr/articles"

[[websites]]
url = "http://mherman.org"

[[websites]]
url = "https://www.miqu.me"

[[websites]]
url = "https://www.mikeash.com/pyblog"

[[websites]]
url = "http://blog.fogus.me"

[[websites]]
url = "https://blog.sleeplessbeastie.eu"

[[websites]]
url = "https://mirocupak.com"

[[websites]]
url = "https://meowni.ca"

[[websites]]
url = "https://blog.monstermuffin.org"

[[websites]]
url = "http://mishadoff.com"

[[websites]]
url = "https://natashatherobot.com"

[[websites]]
url = "https://blog.nelhage.com"

[[websites]]
url = "https://www.thepolyglotdeveloper.com/blog"

[[websites]]
url = "https://nickcraver.com/blog"

[[websites]]
url = "https://nickdesaulniers.github.io"

[[websites]]
url = "http://www.client9.com"

[[websites]]
url = "http://blog.thislongrun.com"

[[websites]]
url = "http://codefx.org"

[[websites]]
url = "http://www.nikola-breznjak.com/blog"

[[websites]]
url = "http://nikolay.rocks"

[[websites]]
url = "http://nshipster.com"

[[websites]]
url = "http://www.nateberkopec.com"

[[websites]]
url = "https://fullstack.info"

[[websites]]
url = "https://oleb.net/blog"

[[websites]]
url = "http://www.windytan.com"

[[websites]]
url = "http://blog.pamelafox.org"

[[websites]]
url = "http://patshaughnessy.net"

[[websites]]
url = "http://www.paulgraham.com/articles.html"

[[websites]]
url = "https://www.paulirish.com"

[[websites]]
url = "https://aerotwist.com/blog"

[[websites]]
url = "https://blog.pchudzik.com"

[[websites]]
url = "http://norvig.com"

[[websites]]
url = "http://petersteinberger.com"

[[websites]]
url = "http://www.catonmat.net/blog"

[[websites]]
url = "http://petr-mitrichev.blogspot.com"

[[websites]]
url = "https://philipwalton.com"

[[websites]]
url = "https://os.phil-opp.com"

[[websites]]
url = "https://ponyfoo.com"

[[websites]]
url = "http://piotrpasich.com"

[[websites]]
url = "http://blog.wittchen.biz.pl"

[[websites]]
url = "https://rachelbythebay.com/w"

[[websites]]
url = "http://radek.io"

[[websites]]
url = "https://radimrehurek.com/blog"

[[websites]]
url = "https://nativeguru.wordpress.com"

[[websites]]
url = "https://www.raywenderlich.com"

[[websites]]
url = "https://blogs.msdn.microsoft.com/oldnewthing"

[[websites]]
url = "https://rhettinger.wordpress.com"

[[websites]]
url = "https://reactjsnews.com"

[[websites]]
url = "https://realpython.com/blog"

[[websites]]
url = "http://raganwald.com/#essays"

[[websites]]
url = "http://regulargeek.com"

[[websites]]
url = "https://akrabat.com"

[[websites]]
url = "http://blog.cleancoder.com"

[[websites]]
url = "https://eviltrout.com"

[[websites]]
url = "http://blog.rtwilson.com"

[[websites]]
url = "http://www.rudyhuyn.com/blog"

[[websites]]
url = "https://neverfriday.com/blog"

[[websites]]
url = "https://ruslanspivak.com"

[[websites]]
url = "https://www.sakib.ninja"

[[websites]]
url = "https://samsaffron.com"

[[websites]]
url = "http://sergeyzhuk.me"

[[websites]]
url = "https://schakko.de"

[[websites]]
url = "http://www.hanselman.com/blog"

[[websites]]
url = "http://www.fuzzyblog.io/blog"

[[websites]]
url = "https://devdactic.com/devblog"

[[websites]]
url = "https://www.9lessons.info"

[[websites]]
url = "http://www.stackabuse.com"

[[websites]]
url = "https://muffinman.io"

[[websites]]
url = "http://codebeforethehorse.tumblr.com"

[[websites]]
url = "http://blog.joda.org"

[[websites]]
url = "https://www.cs.columbia.edu/~smb/blog/control"

[[websites]]
url = "https://steve-yegge.blogspot.com"

[[websites]]
url = "http://sudhagar.com"

[[websites]]
url = "https://swizec.com/blog"

[[websites]]
url = "https://tania.dev"

[[websites]]
url = "http://teropa.info"

[[websites]]
url = "https://thatthinginswift.com"

[[websites]]
url = "http://www.thecodedself.com"

[[websites]]
url = "http://thedailywtf.com"

[[websites]]
url = "http://upcoder.com"

[[websites]]
url = "http://jelv.is/blog"

[[websites]]
url = "https://toddmotto.com"

[[websites]]
url = "http://adventuresinautomation.blogspot.com"

[[websites]]
url = "https://una.im"

[[websites]]
url = "http://undocumentedmatlab.com"

[[websites]]
url = "http://vanillajava.blogspot.com"

[[websites]]
url = "https://vladmihalcea.com"

[[websites]]
url = "http://www.wilfred.me.uk"

[[websites]]
url = "http://www.afronski.pl"

[[websites]]
url = "http://www.yegor256.com"

[[websites]]
url = "http://yifan.lu"

[[websites]]
url = "https://zachholman.com"

[[websites]]
url = "https://zolmeister.com"