[[websites]]
url = "https://jm.dev"

[[websites]]
url = "https://0xadada.pub"

[[websites]]
url = "http://dtrace.org/blogs/ahl"

[[websites]]
url = "https://blog.acolyer.org"

[[websites]]
url = "http://www.brendangregg.com/blog"

[[websites]]
url = "http://dtrace.org/blogs/bmc"

[[websites]]
url = "https://danluu.com"

[[websites]]
url = "http://code.dblock.org"

[[websites]]
url = "https://blog.codinghorror.com"

[[websites]]
url = "https://blog.jessfraz.com"

[[websites]]
url = "https://jvns.ca"

[[websites]]
url = "http://www.paulgraham.com/articles.html"